FROM openjdk:8
EXPOSE 8080
ADD ./scutum-engine-assembly-1.0.jar /opt/scutum/scutum-engine-assembly-1.0.jar
CMD ["java","-jar","/opt/scutum/scutum-engine-assembly-1.0.jar"]
# here we can pass params CMD ["java","-jar","/opt/demo/perimeterx-challange-assembly-1.0.jar host port index fields"]